// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module "vue" {
  export interface GlobalComponents {
    ElAside: typeof import("element-plus/es")["ElAside"];
    ElButton: typeof import("element-plus/es")["ElButton"];
    ElConfigProvider: typeof import("element-plus/es")["ElConfigProvider"];
    ElContainer: typeof import("element-plus/es")["ElContainer"];
    ElForm: typeof import("element-plus/es")["ElForm"];
    ElFormItem: typeof import("element-plus/es")["ElFormItem"];
    ElHeader: typeof import("element-plus/es")["ElHeader"];
    ElIcon: typeof import("element-plus/es")["ElIcon"];
    ElInput: typeof import("element-plus/es")["ElInput"];
    ElMain: typeof import("element-plus/es")["ElMain"];
    ElMenu: typeof import("element-plus/es")["ElMenu"];
    ElMenuItem: typeof import("element-plus/es")["ElMenuItem"];
    Loading: typeof import("element-plus/es")["ElLoadingDirective"];
    SvgIcon: typeof import("./components/SvgIcon.vue")["default"];
  }
}

export {};
